// Tipo de datos para cada ficha
export interface Ficha {
  numero: number;
  nombre: string;
  imagen: any; 
}

// Array con las 90 fichas de la Lotería Campechana
export const FICHAS_LOTERIA: Ficha[] = [
  { numero: 1, nombre: "Martillo", imagen: require('./assets/fichas/1.png') },
  { numero: 2, nombre: "Palomas", imagen: require('./assets/fichas/2.png') },
  { numero: 3, nombre: "Piña", imagen: require('./assets/fichas/3.png') },
  { numero: 4, nombre: "Bruja", imagen: require('./assets/fichas/4.png') },
  { numero: 5, nombre: "Jaula", imagen: require('./assets/fichas/5.png') },
  { numero: 6, nombre: "Gallina", imagen: require('./assets/fichas/6.png') },
  { numero: 7, nombre: "Falúas o Barquitos", imagen: require('./assets/fichas/7.png') },
  { numero: 8, nombre: "Pitos", imagen: require('./assets/fichas/8.png') },
  { numero: 9, nombre: "Pavos", imagen: require('./assets/fichas/9.png') },
  { numero: 10, nombre: "Culebras", imagen: require('./assets/fichas/10.png') },
  { numero: 11, nombre: "Damas", imagen: require('./assets/fichas/11.png') },
  { numero: 12, nombre: "Pescados", imagen: require('./assets/fichas/12.png') },
  { numero: 13, nombre: "Conejos", imagen: require('./assets/fichas/13.png') },
  { numero: 14, nombre: "Gatos", imagen: require('./assets/fichas/14.png') },
  { numero: 15, nombre: "Templos", imagen: require('./assets/fichas/15.png') },
  { numero: 16, nombre: "Venados", imagen: require('./assets/fichas/16.png') },
  { numero: 17, nombre: "Sillas", imagen: require('./assets/fichas/17.png') },
  { numero: 18, nombre: "Uvas", imagen: require('./assets/fichas/18.png') },
  { numero: 19, nombre: "Palacios", imagen: require('./assets/fichas/19.png') },
  { numero: 20, nombre: "Gusanos", imagen: require('./assets/fichas/20.png') },
  { numero: 21, nombre: "Tren", imagen: require('./assets/fichas/21.png') },
  { numero: 22, nombre: "Ahorcados", imagen: require('./assets/fichas/22.png') },
  { numero: 23, nombre: "Melón", imagen: require('./assets/fichas/23.png') },
  { numero: 24, nombre: "Adán y Eva", imagen: require('./assets/fichas/24.png') },
  { numero: 25, nombre: "Caballos", imagen: require('./assets/fichas/25.png') },
  { numero: 26, nombre: "Soldados", imagen: require('./assets/fichas/26.png') },
  { numero: 27, nombre: "Soles", imagen: require('./assets/fichas/27.png') },
  { numero: 28, nombre: "Mulas", imagen: require('./assets/fichas/28.png') },
  { numero: 29, nombre: "Fuertes", imagen: require('./assets/fichas/29.png') },
  { numero: 30, nombre: "Almirez", imagen: require('./assets/fichas/30.png') },
  { numero: 31, nombre: "Quinque", imagen: require('./assets/fichas/31.png') },
  { numero: 32, nombre: "Nopales", imagen: require('./assets/fichas/32.png') },
  { numero: 33, nombre: "Canastas", imagen: require('./assets/fichas/33.png') },
  { numero: 34, nombre: "Águilas", imagen: require('./assets/fichas/34.png') },
  { numero: 35, nombre: "Famas", imagen: require('./assets/fichas/35.png') },
  { numero: 36, nombre: "Cargador", imagen: require('./assets/fichas/36.png') },
  { numero: 37, nombre: "Borrachos", imagen: require('./assets/fichas/37.png') },
  { numero: 38, nombre: "Clarín", imagen: require('./assets/fichas/38.png') },
  { numero: 39, nombre: "Monos", imagen: require('./assets/fichas/39.png') },
  { numero: 40, nombre: "Pabellón o Bandera", imagen: require('./assets/fichas/40.png') },
  { numero: 41, nombre: "Mecedor", imagen: require('./assets/fichas/41.png') },
  { numero: 42, nombre: "Cometa", imagen: require('./assets/fichas/42.png') },
  { numero: 43, nombre: "Luna", imagen: require('./assets/fichas/43.png') },
  { numero: 44, nombre: "Chu", imagen: require('./assets/fichas/44.png') },
  { numero: 45, nombre: "Maromero", imagen: require('./assets/fichas/45.png') },
  { numero: 46, nombre: "Sandía", imagen: require('./assets/fichas/46.png') },
  { numero: 47, nombre: "Negro", imagen: require('./assets/fichas/47.png') },
  { numero: 48, nombre: "Tirador", imagen: require('./assets/fichas/48.png') },
  { numero: 49, nombre: "Sombrero", imagen: require('./assets/fichas/49.png') },
  { numero: 50, nombre: "Mariposa", imagen: require('./assets/fichas/50.png') },
  { numero: 51, nombre: "Chivo", imagen: require('./assets/fichas/51.png') },
  { numero: 52, nombre: "Navaja", imagen: require('./assets/fichas/52.png') },
  { numero: 53, nombre: "Indio", imagen: require('./assets/fichas/53.png') },
  { numero: 54, nombre: "Campana", imagen: require('./assets/fichas/54.png') },
  { numero: 55, nombre: "Mangos", imagen: require('./assets/fichas/55.png') },
  { numero: 56, nombre: "Cachucha", imagen: require('./assets/fichas/56.png') },
  { numero: 57, nombre: "Compás", imagen: require('./assets/fichas/57.png') },
  { numero: 58, nombre: "Corazón", imagen: require('./assets/fichas/58.png') },
  { numero: 59, nombre: "Sierras", imagen: require('./assets/fichas/59.png') },
  { numero: 60, nombre: "Granadas", imagen: require('./assets/fichas/60.png') },
  { numero: 61, nombre: "Toros", imagen: require('./assets/fichas/61.png') },
  { numero: 62, nombre: "León", imagen: require('./assets/fichas/62.png') },
  { numero: 63, nombre: "Bailarina", imagen: require('./assets/fichas/63.png') },
  { numero: 64, nombre: "Corona", imagen: require('./assets/fichas/64.png') },
  { numero: 65, nombre: "Volcán", imagen: require('./assets/fichas/65.png') },
  { numero: 66, nombre: "Perro", imagen: require('./assets/fichas/66.png') },
  { numero: 67, nombre: "Palma", imagen: require('./assets/fichas/67.png') },
  { numero: 68, nombre: "Dados", imagen: require('./assets/fichas/68.png') },
  { numero: 69, nombre: "Fresa", imagen: require('./assets/fichas/69.png') },
  { numero: 70, nombre: "Tecolote", imagen: require('./assets/fichas/70.png') },
  { numero: 71, nombre: "Bota", imagen: require('./assets/fichas/71.png') },
  { numero: 72, nombre: "Árbol", imagen: require('./assets/fichas/72.png') },
  { numero: 73, nombre: "Rosas", imagen: require('./assets/fichas/73.png') },
  { numero: 74, nombre: "Perico", imagen: require('./assets/fichas/74.png') },
  { numero: 75, nombre: "Botella", imagen: require('./assets/fichas/75.png') },
  { numero: 76, nombre: "Higo", imagen: require('./assets/fichas/76.png') },
  { numero: 77, nombre: "Guitarra", imagen: require('./assets/fichas/77.png') },
  { numero: 78, nombre: "Manzana", imagen: require('./assets/fichas/78.png') },
  { numero: 79, nombre: "Jarra", imagen: require('./assets/fichas/79.png') },
  { numero: 80, nombre: "Lira", imagen: require('./assets/fichas/80.png') },
  { numero: 81, nombre: "Vapor", imagen: require('./assets/fichas/81.png') },
  { numero: 82, nombre: "Ancla", imagen: require('./assets/fichas/82.png') },
  { numero: 83, nombre: "Garza", imagen: require('./assets/fichas/83.png') },
  { numero: 84, nombre: "Globos", imagen: require('./assets/fichas/84.png') },
  { numero: 85, nombre: "Panzón", imagen: require('./assets/fichas/85.png') },
  { numero: 86, nombre: "Ciprés", imagen: require('./assets/fichas/86.png') },
  { numero: 87, nombre: "Casa", imagen: require('./assets/fichas/87.png') },
  { numero: 88, nombre: "Patones o Flamenco", imagen: require('./assets/fichas/88.png') },
  { numero: 89, nombre: "Almohadilla", imagen: require('./assets/fichas/89.png') },
  { numero: 90, nombre: "Mundo", imagen: require('./assets/fichas/90.png') },
];

// Función para obtener una ficha por su número
export const obtenerFichaPorNumero = (numero: number): Ficha | undefined => {
  return FICHAS_LOTERIA.find(ficha => ficha.numero === numero);
};